### ISSUE TITLE
多卡并行如何更新centers？

### ISSUE THREAD

**Issue by lipond** [EncodeTS/TensorFlow_Center_Loss#2]
As the title, tks.

**Comment by EncodeTS** [comment]
不好意思，现在才注意到，最近确实没有精力去研究多卡的实现，实在抱歉啦

**Comment by vzxxbacq** [comment]
@lipond @EncodeTS ，用一个全为0的矩阵替换掉原来的center进行scatter_sub，就可以用这个矩阵来保存对于每个类的中心最终要修改多少。每个GPU上计算出来的这个矩阵进行求和再与center相加，就是最后的结果，如果作者需要的话我可以提一个PR。

**Comment by EncodeTS** [comment]
@vzxxbacq 欢迎PR哈👍
