### ISSUE TITLE
center points 更新实现和论文不一致

### ISSUE THREAD

**Issue by jasstionzyf** [EncodeTS/TensorFlow_Center_Loss#3]
参考论文里面(4)这个公式，在更新center points 的时候是不是应该只考虑用分类正确的features来更新center points？

**Comment by EncodeTS** [comment]
公式(4)，按我的理解是每个样本都会对其自身类别的“center“更新有贡献，代码确实也是这样实现的，我没看出来哪里有问题，请指教

**Comment by jasstionzyf** [comment]
@EncodeTS    公式(4)里面有个δ(yi = j) ，  表示只有当分类结果正确的特征才会去更新类中心点，  而不是当前批量里面所有的特征都去更新

**Comment by EncodeTS** [comment]
这里的y_i不是代表网络的分类结果，而是样本的真实类别，这个公式本身与分类结果是没有关系的。之所以用到y_i，是为了表示每个样本的特征向量只对**这个样本对应的真实类别(即y_i)**有贡献

**Comment by EncodeTS** [comment]
> @EncodeTS 公式(4)里面有个δ(yi = j) ， 表示只有当分类结果正确的特征才会去更新类中心点， 而不是当前批量里面所有的特征都去更新

@jasstionzyf 这里的y_i不是代表网络的分类结果，而是样本的真实类别，这个公式本身与分类结果是没有关系的。之所以用到y_i，是为了表示每个样本的特征向量只对**这个样本对应的真实类别(即y_i)**有贡献

**Comment by jasstionzyf** [comment]
@EncodeTS   你是对的，  多谢！
