### ISSUE TITLE
如何理解串行全连接

### ISSUE THREAD

**Issue by DotaArtist** [EncodeTS/TensorFlow_Center_Loss#4]
![image](https://user-images.githubusercontent.com/15724139/52770742-e0f1f580-306e-11e9-98d1-ced8ad1aaa3b.png)
在原有网络上添加center loss 更改了原有网络结构，因为添加了hidden_dim == center_dim的全连接层。
改成并行的两个全连接：
x = slim.flatten(x, scope='flatten')      
feature = slim.fully_connected(x, num_outputs=2, activation_fn=None, scope='fc1')
x = slim.fully_connected(x, num_outputs=10, activation_fn=None, scope='fc2')
这样不会改变原结构，只是加了一个分支训练。求大神指正。。。

**Comment by DotaArtist** [comment]
@EncodeTS

**Comment by EncodeTS** [comment]
这里只是为了在函数return的时候能拿到中间的feature向量以便于后续加入center loss，没有其他特别的含义
