### ISSUE TITLE
center loss 计算问题

### ISSUE THREAD

**Issue by mJackie** [EncodeTS/TensorFlow_Center_Loss#5]
在每个batch中计算loss的时候，代码中是以每个batch中类别的中心。
按照paper中，应该是以当前经过网络的所有数据的中心计算吧，即centers_update_op
代码中的 centers_update_op 有什么用？看到只是一个返回值

**Comment by mJackie** [comment]
是否方便加qq讨论

**Comment by EncodeTS** [comment]
@mJackie centers_update_op是一个op，用于更新centers这个tensor，因此在每一步训练中都需要去执行。你如果要获取各个类别的中心向量，可以用返回的centers。
