### ISSUE TITLE
Division by batch size

### ISSUE THREAD

**Issue by hbellafkir** [EncodeTS/TensorFlow_Center_Loss#6]
hi,
https://github.com/EncodeTS/TensorFlow_Center_Loss/blob/a5c1ad76b77248d7c910334e54c36bc6bd20dbcd/center_loss.py#L31
you need to divide here by the batch size I think

**Comment by EncodeTS** [comment]
![image](https://user-images.githubusercontent.com/16507370/62823694-55dd5c80-bbc6-11e9-82a6-45c1aa9aab51.png)
Hi, @hbellafkir. I’m implementing this according to the formula (2) in the paper. You can divide the loss by the batch size later or you can process them in some other ways, I leave that flexibility to the user.
